In [27]:
import torch 
temp_data_C=torch.randint(-10,41,(30,))
temp_data_F=9*temp_data_C/5 +32
print("Data in Celcius: \n",temp_data_C)
print("Data in Fahrenheit: \n",temp_data_F)
temp_max= temp_data_C.max()
temp_min=temp_data_C.min()
temp_range=temp_max-temp_min
print("Temperature Range: ",temp_range.item())
temp_avg=temp_data_C.float().mean()
print("Mean Temperature: ",temp_avg.item())
temp_var=temp_data_C.float().std(dim=0)
var_station=torch.argmax(temp_var).item()
hot=torch.argmax(temp_data_C.max(dim=0).values).item()
print(f"Highest Variability Station: Station {chr(var_station+65)}")
print(f"Hottest Day: Day {hot + 1}")



Data in Celcius: 
 tensor([ -4,  34,  -9,  24,   9,   3,   1,   4,  21,  34,  28,  27,  28,   3,
         -8,  16,   0,   8,  12,   7, -10,  36, -10,  17,  -4,  19,  -5,   7,
         -9,  -8])
Data in Fahrenheit: 
 tensor([24.8000, 93.2000, 15.8000, 75.2000, 48.2000, 37.4000, 33.8000, 39.2000,
        69.8000, 93.2000, 82.4000, 80.6000, 82.4000, 37.4000, 17.6000, 60.8000,
        32.0000, 46.4000, 53.6000, 44.6000, 14.0000, 96.8000, 14.0000, 62.6000,
        24.8000, 66.2000, 23.0000, 44.6000, 15.8000, 17.6000])
Temperature Range:  46
Mean Temperature:  9.033333778381348
Highest Variability Station: Station C
Hottest Day: Day 1


In [24]:
import torch
temp_data = torch.randint(-10,41,(30,))
print("Daily Temperatures for 30 days in C:\n",temp_data)
temp_station = ["Station A","Station B","Station C","Station D","Station E"]
weather = torch.randint(-10,41,(10,5))
print("Weather (10 rows * 5 columns):\n", weather)
temp_mean = weather.float().mean(dim=0)
temp_max=weather.max(dim=0).values
temp_min= weather.min(dim=0).values
print("\nStationwise Analysis: ")
for i, station in enumerate(temp_station):
    print(f"{station}: Mean={temp_mean[i]:.2f}°C, Max={temp_max[i]}°C, Min={temp_min[i]}°C")


Daily Temperatures for 30 days in C:
 tensor([ -2,  18,  40,  32,  31,  35,  35,  14,  22,  -8,  12,  13,  24,  19,
          3,  32,   1,  17,  26,  35, -10,  -4,  25,  30,  14,  19,  21,  37,
         12,  -4])
Weather (10 rows * 5 columns):
 tensor([[38, 11, -7, 33, -9],
        [ 0, 17, 30, 32, 12],
        [36,  1, 38, 38, -4],
        [ 3,  9,  8, -3,  0],
        [25, 31,  4, 33,  9],
        [ 0,  8, 20, -3, -9],
        [14, 27, 11, 28, 22],
        [11, 22, 14, 39, 39],
        [ 4, 37, 29, 16,  6],
        [12, 28, 14, 31,  2]])

Stationwise Analysis: 
Station A: Mean=14.30°C, Max=38°C, Min=0°C
Station B: Mean=19.10°C, Max=37°C, Min=1°C
Station C: Mean=16.10°C, Max=38°C, Min=-7°C
Station D: Mean=24.40°C, Max=39°C, Min=-3°C
Station E: Mean=6.80°C, Max=39°C, Min=-9°C
